config/routes.rb
Positronic::Application.routes.draw do
  root :to => 'home#index'
  resources :pages, :only => [:index, :show] do
    member do
      get :traffic_chart
    end
    collection do
      get :panda_impact_summary
      get :totals
      get :aggregate
      post :setdate
      get :comparison_test
      get :graphs
      get :details
      get :overview
      get :publishedcontent
    end
  end

  # data routes
  scope "data" do
    match "/groups", to: "data#groups", :as => 'data_groups'
  end

  resources :contributors, :only => [:show] do
    member do
      get :contributions
      get :metacontributions
    end
  end

  resources :nodes, :only => [:index, :show] do
    collection do
      get :graphs
      get :details
      get :list
    end
  end


  resources :groups, :only => [:index, :show] do
    collection do
      get :list
    end
    member do
      get :pagelist
      get :pages
      get :pagetags
      get :nodes
      get :node_graphs
      get :node_activity
    end
  end


  # aae notice
  match '/aae', to: 'home#aae', :as => 'aae_notice'

  # authentication
  match '/logout', to:'auth#end', :as => 'logout'
  match '/auth/:provider/callback', to: 'auth#success'

  # home routes
  match '/search', to:'home#search', :as => 'search'

  # experiments named routes
  match '/experiments', to: 'experiments#index', :as => 'experiments'

  # catch all
  match '/:controller(/:action(/:id))'

end

app/models/node.rb
# === COPYRIGHT:
#  Copyright (c) North Carolina State University
#  Developed with funding for the National eXtension Initiative.
# === LICENSE:
#
#  see LICENSE file

class Node < ActiveRecord::Base
  include CacheTools
  extend YearWeek
  has_one :page
  has_many :node_groups
  has_many :groups, :through => :node_groups
  has_many :aae_nodes
  has_many :node_activities
  has_many :node_metacontributions
  has_many :meta_contributors, :through => :node_metacontributions, :source => :contributor
  has_many :activity_contributors, :through => :node_activities, :source => :contributor

  # datatypes that we care about
  PUBLISHED_TYPES = ['article','faq','news']

  scope :by_datatype, lambda{|datatype|
    case datatype
    when 'all'
      where(1)
    else
      where("node_type = ?",datatype)
    end
  }

  # used as a sanitycheck list
  NODE_SCOPES = ['all_nodes','publishables','articles','faqs','news','administrative','forums','group_admin','extension_admin','other']
  PUBLISHED_NODE_SCOPES = ['articles','faqs','news']
  ADMINISTRATIVE_NODE_SCOPES = ['forums','group_admin','extension_admin','other']
  ADMINISTRATIVE_TYPES = ['forum','cop_document','public_article']

  ADMINISTRATIVE_NODE_SCOPES_LABELS = {'forums' => 'Forums',
                                       'group_admin' => 'Group Admin',
                                       'extension_admin' => 'eXtension Admin',
                                       'other' => 'Other'}

  scope :all_nodes, where(1) # just a convenience scope for scoping node types and activity types
  
  scope :articles, where(node_type: 'article')
  scope :faqs,     where(node_type: 'faq')
  scope :news,     where(node_type: 'news')
  scope :publishables, where("node_type IN (#{PUBLISHED_TYPES.collect{|type| quote_value(type)}.join(', ')})")
  scope :administrative,  where("node_type NOT IN (#{PUBLISHED_TYPES.collect{|type| quote_value(type)}.join(', ')})")
  scope :forums,          where(node_type: 'forum')
  scope :group_admin,     where(node_type: 'cop_document')
  scope :extension_admin, where(node_type: 'public_article')
  scope :other,           where("node_type NOT IN (#{(PUBLISHED_TYPES + ADMINISTRATIVE_TYPES).collect{|type| quote_value(type)}.join(', ')})")

  scope :has_page, where(:has_page => true)
  scope :created_since, lambda {|date| where("#{self.table_name}.created_at >= ?",date).order("#{self.table_name}.created_at")}

  scope :latest_activity, lambda{
    yearweek = Analytic.latest_yearweek
    joins(:node_activities).where("YEARWEEK(node_activities.created_at,3) = ?",yearweek)
  }

  scope :reviewed, lambda {
    joins(:node_activities).where('node_activities.activity = ?',NodeActivity::REVIEW_ACTIVITY).select("distinct(#{self.table_name}.id),#{self.table_name}.*")
  }

  def display_title(options = {})
    truncate_it = options[:truncate].nil? ? true : options[:truncate]

    if(self.title.blank?)
      display_title = '(blank)'
    elsif(truncate_it)
      display_title = self.title.truncate(80, :separator => ' ')
    else
      display_title = self.title
    end
    display_title
  end

  def contributions_by_contributor
    self.activity_contributors.group("contributors.id").select("contributors.*, group_concat(node_activities.event) as contributions")
  end

  def meta_contributions_by_contributor
    self.meta_contributors.group("contributors.id").select("contributors.*, group_concat(node_metacontributions.role) as metacontributions")
  end

  def contributions_count
    counts = {}
    counts[:contributors] = self.node_activities.count('contributor_id',:distinct => true)
    counts[:actions] = self.node_activities.count
    counts[:byaction] = self.node_activities.group('event').count
    counts
  end

  def metacontributions_count
    counts = {}
    counts[:contributors] = self.node_metacontributions.count('contributor_id',:distinct => true)
    counts[:actions] = self.node_metacontributions.count
    counts[:byaction] = self.node_metacontributions.group('role').count
    counts
  end

  def self.rebuild
    self.connection.execute("truncate table #{self.table_name};")
    CreateNode.find_in_batches do |group|
      insert_values = []
      group.each do |node|
        insert_list = []
        insert_list << node.nid
        insert_list << node.vid
        insert_list << ActiveRecord::Base.quote_value(node.type)
        insert_list << ActiveRecord::Base.quote_value(node.title)
        insert_list << ActiveRecord::Base.quote_value(node.created_at.to_s(:db))
        insert_list << ActiveRecord::Base.quote_value(node.updated_at.to_s(:db))
        insert_values << "(#{insert_list.join(',')})"
      end
      insert_sql = "INSERT INTO #{self.table_name} (id,revision_id,node_type,title,created_at,updated_at) VALUES #{insert_values.join(',')};"
      self.connection.execute(insert_sql)
    end

    # set page flag
    update_sql = "UPDATE #{self.table_name},#{Page.table_name} SET #{self.table_name}.has_page = 1 WHERE #{self.table_name}.id = #{Page.table_name}.node_id and #{Page.table_name}.source = 'create'"
    self.connection.execute(update_sql)
    true
  end

  def self.counts_by_yearweek
    with_scope do
      self.group("YEARWEEK(#{self.table_name}.created_at,3)").count
    end
  end

  def self.published_since(date)
    joins(:node_activities).where("node_activities.event = #{NodeActivity::PUBLISHED}").where("node_activities.created_at > ?",date).select("distinct(#{self.table_name}.id),#{self.table_name}.*")
  end

  def self.earliest_created_at
    with_scope do
      self.minimum(:created_at)
    end
  end

  def overall_stats(activity)
    stats = {}
    contributors_count =  "COUNT(DISTINCT(node_activities.contributor_id)) as contributors"
    contributions_count =  "COUNT(DISTINCT(node_activities.id)) as contributions"

    scope = self.node_activities
    if(activity != NodeActivity::ALL_ACTIVITY)
      scope = scope.where('node_activities.activity = ?',activity)
    end
    result = scope.select("#{contributions_count}, #{contributors_count}").first
    stats = {contributions: result.contributions, contributors: result.contributors}
    stats
  end

  def self.overall_stats(activity,cache_options = {})
    if(!cache_options[:nocache])
      cache_key = self.get_cache_key(__method__,{activity: activity, scope_sql: current_scope ? current_scope.to_sql : ''})
      Rails.cache.fetch(cache_key,cache_options) do
        with_scope do
          _overall_stats(activity)
        end
      end
    else
      with_scope do
        _overall_stats(activity)
      end
    end
  end

  def self._overall_stats(activity)
    stats = {}
    with_scope do
      contributors_count =  "COUNT(DISTINCT(node_activities.contributor_id)) as contributors"
      contributions_count =  "COUNT(DISTINCT(node_activities.id)) as contributions"
      items_count = "COUNT(DISTINCT(node_activities.node_id)) as items"

      scope = self.joins(:node_activities)
      if(activity != NodeActivity::ALL_ACTIVITY)
        scope = scope.where('node_activities.activity = ?',activity)
      end
      result = scope.select("#{contributions_count}, #{contributors_count}, #{items_count}").first
      stats = {contributions: result.contributions, contributors: result.contributors, items: result.items}
    end
    stats
  end

  def stats_by_yearweek(activity,cache_options = {})
    if(!cache_options[:nocache])
      cache_key = self.get_cache_key(__method__,{activity: activity})
      Rails.cache.fetch(cache_key,cache_options) do
        _stats_by_yearweek(activity)
      end
    else
      _stats_by_yearweek(activity)
    end
  end

  def _stats_by_yearweek(activity)
    stats = YearWeekStats.new
    yearweek_condition = "YEARWEEK(node_activities.created_at,3)"
    contributors_count =  "COUNT(DISTINCT(node_activities.contributor_id)) as contributors"
    contributions_count =  "COUNT(DISTINCT(node_activities.id)) as contributions"

    scope = self.node_activities.group(yearweek_condition)
    if(activity != NodeActivity::ALL_ACTIVITY)
      scope = scope.where('node_activities.activity = ?',activity)
    end
    week_stats_query = scope.select("#{yearweek_condition} as yearweek, #{contributions_count}, #{contributors_count}")

    weekstats_by_yearweek = {}
    week_stats_query.each do |ws|
      weekstats_by_yearweek[ws.yearweek] = {contributions: ws.contributions, contributors: ws.contributors}
    end

    eligible_year_weeks.each do |year,week|
      yearweek = self.class.yearweek(year,week)
      if(weekstats_by_yearweek[yearweek])
        stats[yearweek] = weekstats_by_yearweek[yearweek]
      else
        stats[yearweek] = {contributions: 0, contributors: 0}
      end
    end
    stats
  end


  def self.stats_by_yearweek(activity,cache_options = {})
    if(!cache_options[:nocache])
      cache_key = self.get_cache_key(__method__,{activity: activity, scope_sql: current_scope ? current_scope.to_sql : ''})
      Rails.cache.fetch(cache_key,cache_options) do
        with_scope do
          _stats_by_yearweek(activity)
        end
      end
    else
      with_scope do
        _stats_by_yearweek(activity)
      end
    end
  end

  def self._stats_by_yearweek(activity)
    stats = YearWeekStats.new
    with_scope do
      yearweek_condition = "YEARWEEK(node_activities.created_at,3)"
      contributors_count =  "COUNT(DISTINCT(node_activities.contributor_id)) as contributors"
      contributions_count =  "COUNT(DISTINCT(node_activities.id)) as contributions"
      items_count = "COUNT(DISTINCT(node_activities.node_id)) as items"

      scope = self.joins(:node_activities).group(yearweek_condition)
      if(activity != NodeActivity::ALL_ACTIVITY)
        scope = scope.where('node_activities.activity = ?',activity)
      end
      week_stats_query = scope.select("#{yearweek_condition} as yearweek, #{contributions_count}, #{contributors_count}, #{items_count}")

      weekstats_by_yearweek = {}
      week_stats_query.each do |ws|

app/controllers/nodes_controller.rb
# === COPYRIGHT:
#  Copyright (c) North Carolina State University
#  Developed with funding for the National eXtension Initiative.
# === LICENSE:
#
#  see LICENSE file

class NodesController < ApplicationController
  before_filter :check_for_group
  helper_method :display_node_scope

  def index
    @activity = params[:activity]
    if(!NodeActivity::ACTIVITIES.include?(@activity))
      # for now, error later
      @activity =  NodeActivity::ALL_ACTIVITY
    end

    # this is a crapton of stats
    @overall_everything_stats = Node.overall_stats(@activity)
    @lastweek_everything_stats = Node.latest_activity.overall_stats(@activity)
    @everything_stats_by_week = Node.stats_by_yearweek(@activity)

    @overall_publishable_stats = YearWeekStatsComparator.new
    @lastweek_publishable_stats = YearWeekStatsComparator.new
    @publishable_stats_by_week = YearWeekStatsComparator.new
    Node::PUBLISHED_NODE_SCOPES.each do |node_scope|
      @overall_publishable_stats[node_scope] = Node.send(node_scope).overall_stats(@activity)
      @lastweek_publishable_stats[node_scope] = Node.send(node_scope).latest_activity.overall_stats(@activity)
      @publishable_stats_by_week[node_scope] = Node.send(node_scope).stats_by_yearweek(@activity)
    end

    @overall_administrative_stats = YearWeekStatsComparator.new
    @lastweek_administrative_stats = YearWeekStatsComparator.new
    @administrative_stats_by_week = YearWeekStatsComparator.new
    Node::ADMINISTRATIVE_NODE_SCOPES.each do |node_scope|
      @overall_administrative_stats[node_scope] = Node.send(node_scope).overall_stats(@activity)
      @lastweek_administrative_stats[node_scope] = Node.send(node_scope).latest_activity.overall_stats(@activity)
      @administrative_stats_by_week[node_scope] = Node.send(node_scope).stats_by_yearweek(@activity)
    end

  end

  def show
    @node = Node.find(params[:id])
  end

  def graphs
    if(params[:group])
      @group = Group.find(params[:group])
    end

    @node_scope = params[:node_scope]
    if(!Node::NODE_SCOPES.include?(@node_scope))
      @node_scope = 'all_nodes'
    end

    @activity = params[:activity]
    if(!NodeActivity::ACTIVITIES.include?(@activity))
      # for now, error later
      @activity =  NodeActivity::ALL_ACTIVITY
    end
  end

  def details
    @node_scope = params[:node_scope]
    if(!Node::NODE_SCOPES.include?(@node_scope))
      @node_scope = 'all_nodes'
    end

    # todo: contributor, tags
    if(@group)
      scope = @group.nodes.send(@node_scope)
    else
      scope = Node.send(@node_scope)
    end

    @page_title_display = @page_title = "#{display_node_scope} Details"
    @endpoint = display_node_scope

    if(@group)
      @page_title += " - Group ##{@group.id}"
      @page_title_display += " for #{@group.name}"
    end

    @activity_stats = YearWeekStatsComparator.new
    NodeActivity::ACTIVITIES.each do |activity|
      @activity_stats[activity] = scope.stats_by_yearweek(activity)
    end

  end

  def list
    @node_scope = params[:node_scope]
    if(!Node::NODE_SCOPES.include?(@node_scope))
      @node_scope = 'all_nodes'
    end

    # todo: contributor, tags
    if(@group)
      scope = @group.nodes.send(@node_scope)
    else
      scope = Node.send(@node_scope)
    end

    # order_by
    if(params[:order_by] and Node.column_names.include?(params[:order_by]))
      @order_by = params[:order_by]
    else
      @order_by = 'created_at'
    end

    # direction
    if(params[:direction] and %w[asc desc].include?(params[:direction]))
      @direction = params[:direction]
    else
      @direction = 'asc'
    end

    @page_title_display = @page_title = "#{display_node_scope} Node List"
    @endpoint = "Node List"

    if(@group)
      @page_title += " - Group ##{@group.id}"
      @page_title_display += " for #{@group.name}"
    end


    @nodelist = scope.order("#{@order_by} #{@direction}").page(params[:page])

  end

  protected

  def display_node_scope
    @node_scope.gsub('_',' ').titleize
  end

  def check_for_group
    if(params[:group_id])
      @group = Group.find(params[:group_id])
    end
    true
  end

end

app/helpers/nodes_helper.rb
# encoding: utf-8
# === COPYRIGHT:
# Copyright (c) 2012 North Carolina State University
# === LICENSE:
# see LICENSE file

module NodesHelper

	def node_scope_label(node_scope)
		if(node_scope == 'all_nodes')
			'All Content'
		else
			node_scope.capitalize
		end
	end

	def activity_scope_label(activity_scope)
		if(activity_scope == 'all_activity')
			'All'
		else
			activity_scope.capitalize
		end
	end

	def node_title_display(node,options = {})
		link_to(node.display_title(options),node_path(node)).html_safe
	end

	def node_page_title_display(node,options = {})
		if(node.has_page?)
			link_to("Page ##{node.page.id}",page_path(node.page)).html_safe
		else
			'not published'
		end
	end

	def graph_nav_li(activity)
		listclass = 'active' if activity == @activity
		if(activity == NodeActivity::ALL_ACTIVITY)
			label = 'All'
		else
			label = activity.pluralize.capitalize
		end
		nav_li = '<li'
		if(listclass.present?)
			nav_li += " class=#{listclass}"
		end
		nav_li += '>'
		nav_li += link_to(label,graphs_nodes_path(:node_scope => @node_scope, :activity => activity))
		nav_li += '</li>'
		nav_li.html_safe
	end

  def c_i_c_text(stats)
    returnstring = <<-END
    <p><span class='mednumber'>#{stats[:contributions]}</span> contributions</p>
    <p>of <span class='mednumber'>#{stats[:items]}</span> items</p>
    <p>by <span class='mednumber'>#{stats[:contributors]}</span> contributors</p>
    END
    returnstring.html_safe
  end





end

app/views/nodes/_group_node_breadcrumbs.html.erb
<%- # TODO: there have to be better ways of doing this that utilize the action names -%>
<ul class="breadcrumb">
  <li><%= link_to('Groups',groups_path) %><span class="divider">/</span></li>
  <li><%= link_to(@group.name, group_path(@group)) %><span class="divider">/</span></li>
  <li><%= link_to('Nodes','#') %><span class="divider">/</span></li>

  <%- if @node_scope and (!local_assigns.has_key?(:endpoint) or endpoint != display_node_scope) -%>
  <li><%= link_to(display_node_scope,details_nodes_path(node_scope: @node_scope, group_id: @group.id)) %><span class="divider">/</span></li>
  <%- end -%>

  <%- if local_assigns.has_key?(:endpoint) and endpoint != 'Nodes'-%>
  <li class='active'><%= endpoint %></li>
  <%- end -%>
</ul>


  <li>
    <%- if local_assigns.has_key?(:endpoint) and endpoint == 'Nodes' -%>
      Nodes<span class="divider">/</span>
    <%- else -%>
      <%= link_to('Nodes',nodes_path) %><span class="divider">/</span>
    <%- end -%>
  </li>

  <%- if @node_scope and (!local_assigns.has_key?(:endpoint) or endpoint != display_node_scope) -%>
  <li><%= link_to(display_node_scope,details_nodes_path(node_scope: @node_scope)) %><span class="divider">/</span></li>
  <%- end -%>

app/views/nodes/_node_breadcrumbs.html.erb
<%- # TODO: there have to be better ways of doing this that utilize the action names -%>
<ul class="breadcrumb">
  <li>
    <%- if local_assigns.has_key?(:endpoint) and endpoint == 'Nodes' -%>
      Nodes<span class="divider">/</span>
    <%- else -%>
      <%= link_to('Nodes',nodes_path) %><span class="divider">/</span>
    <%- end -%>
  </li>

  <%- if @node_scope and (!local_assigns.has_key?(:endpoint) or endpoint != display_node_scope) -%>
  <li><%= link_to(display_node_scope,details_nodes_path(node_scope: @node_scope)) %><span class="divider">/</span></li>
  <%- end -%>

  <%- if local_assigns.has_key?(:endpoint) and endpoint != 'Nodes'-%>
  <li class='active'><%= endpoint %></li>
  <%- end -%>
</ul>

app/views/nodes/details.html.erb
<%- if @group -%>
  <%= render(:partial => 'group_node_breadcrumbs', :locals => {:endpoint => @endpoint}) %>
<%- else -%>
  <%= render(:partial => 'node_breadcrumbs', :locals => {:endpoint => @endpoint}) %>
<%- end -%>
<header class="jumbotron subhead" id="overview">
  <h1><%= @page_title_display.html_safe %></h1>
  <p class="lead">Data for <%= year_week_for_last_week%> (<%= date_range_for_last_week%>)</p>
</header>

<div class="page-header">
  <h2>Summary</h2>
  <%- link_params = params.delete_if{|k,v| ['action'].include?(k)} -%>
  <%= link_to("Node List &raquo;".html_safe,list_nodes_path(link_params),:class => 'btn') %></p>
</div>


<div class="row">
<div class="span12">
  <h3>Contributors</h3>
  <%= render(:partial => 'shared/comparison_plot',
             :locals => {data: @activity_stats.to_graph_data(:contributors),
                         labels: @activity_stats.to_graph_labels,
                         datalabel: "contributors" }) -%>
</div>
</div>

<div class="row">
<div class="span12">
  <h3>Contributions</h3>
  <%= render(:partial => 'shared/comparison_plot',
             :locals => {data: @activity_stats.to_graph_data(:contributions),
                         labels: @activity_stats.to_graph_labels,
                         datalabel: "contributions" }) -%>
</div>
</div>

<div class="row">
<div class="span12">
  <h3>Items</h3>
  <%= render(:partial => 'shared/comparison_plot',
             :locals => {data: @activity_stats.to_graph_data(:items),
                         labels: @activity_stats.to_graph_labels,
                         datalabel: "items" }) -%>
</div>
</div>

app/views/nodes/graphs.html.erb
<%-
	if @group.nil?
      @page_title = "#{node_scope_label(@node_scope)} Activity Graphs "
      @page_title_display = "#{node_scope_label(@node_scope)} Activity Graphs "
    else
      @page_title = "#{node_scope_label(@node_scope)} Activity Graphs for Group ##{@group.id}"
      @page_title_display = "#{node_scope_label(@node_scope)} Activity Graphs for #{@group.name}"
    end
-%>
<header class="jumbotron subhead" id="overview">
  <h1><%= @page_title_display %></h1>
  <p class="lead">Data for <%= year_week_for_last_week%> (<%= date_range_for_last_week%>) </p>
</header>

<ul class="nav nav-tabs">
  <%- NodeActivity::ACTIVITIES.each do |activity| -%>
  <%= graph_nav_li(activity) %>
  <%- end -%>
</ul>

<%- ['contributions','items','contributors'].each do |metric| -%>
<div class="page-header">
  <h1><%= activity_scope_label(@activity) %> - <%= metric.capitalize %></h1>
</div>
<div class="row">
  <div class="span12">
    <%- if(@group.nil?)
          stats_scope = Node.send(@node_scope)
        else
          stats_scope = @group.nodes.send(@node_scope)
        end %>
    <%= render(:partial => 'shared/line_plot', :locals => {:data => stats_scope.stats_by_yearweek(@activity).to_graph_data(metric.to_sym), :datalabel => metric })%>
  </div>
</div>
<%- end -%>

app/views/nodes/show.html.erb
<% @page_title = "Details for Node ##{@node.id}" %>
<header class="jumbotron subhead" id="overview">
  <h1><%= @page_title %></h1>
  <p class="lead">Data for <%= year_week_for_last_week%> (<%= date_range_for_last_week%>) </p>
</header>


<div class="page-header">
  <h1>Activity</h1>
</div>
<div class="row">
  <div class="span4">
    <h3>Contributions</h3>
    <%- activity_counts = @node.contributions_count -%>
    <%- if(activity_counts[:contributors] > 0 ) -%>
     <dl>
      <dt><span class='regnumber'><%= activity_counts[:actions] %></span> contributions by <span class='regnumber'><%= activity_counts[:contributors] %></span> contributors</dt>
      <%- activity_counts[:byaction].keys.each do |action| -%>
      <dd><span class='regnumber'><%= activity_counts[:byaction][action] %></span> <%= NodeActivity.event_to_s(action) %></dd>
      <%- end -%>
    <%- else -%>
      <p>none</p>
    <%- end -%>

    <%- if(Node::PUBLISHED_TYPES.include?(@node.node_type)) -%>
    <hr/>
    <h3>Listed Contributions</h3>
    <%- meta_activity_counts = @node.metacontributions_count -%>
    <%- if(meta_activity_counts[:contributors] > 0 ) -%>
     <dl>
      <dt><span class='regnumber'><%= meta_activity_counts[:actions] %></span> contributions by <span class='regnumber'><%= meta_activity_counts[:contributors] %></span> contributors</dt>
      <%- meta_activity_counts[:byaction].keys.each do |action| -%>
      <dd><span class='regnumber'><%= meta_activity_counts[:byaction][action] %></span> <%= action %></dd>
      <%- end -%>
    <%- else -%>
      <p>none</p>
    <%- end -%>
    <%- end -%>

  </div>

  <div class="span8">
    <h3>Contributions by week</h3>
    <%= render(:partial => 'shared/line_plot', :locals => {:data => @node.stats_by_yearweek(NodeActivity::ALL_ACTIVITY).to_graph_data(:contributions,{showrolling:false}), :datalabel => @node.id })%>
  </div>
</div>

<div class="row">
  <div class="span12">
	 <h3>Node Information</h3>
	<table class="table table-bordered">

	  <tbody>
      <tr>
        <td>Title</td>
        <td><%= @node.title %></td>
      </tr>
      <tr>
        <td>Node Type</td>
        <td><%= @node.node_type %></td>
      </tr>
      <tr>
        <td>Published?</td>
        <td>
          <%- if @node.has_page? -%>
            Yes. (<%= link_to("Page ID ##{@node.page.id}",page_path(@node.page)) %>)
          <%- else -%>
            No.
          <%- end -%>
        </td>
      </tr>
      <tr>
        <td>Groups</td>
        <td><%= @node.groups.map{|g| g.name}.join(', ').html_safe %></td>
      </tr>
      <tr>
      <tr>
        <td>@ Create</td>
        <td><%= link_to("http://create.extension.org/node/#{@node.id}","http://create.extension.org/node/#{@node.id}")%></td>
      </tr>
      <tr>
        <td>Contributors</td>
        <td>
          <%- @node.contributions_by_contributor.each do |contributor| -%>
            <p>
              <%= link_to(contributor.fullname, contributor_path(contributor)) %>
              : <%= NodeActivity.contributions_display(contributor.contributions).html_safe %>
            </p>
          <%- end -%>
        </td>
      </tr>
      <tr>
        <td>Listed contributors</td>
        <%- if (Node::PUBLISHED_TYPES.include?(@node.node_type)) and (meta_activity_counts[:contributors] > 0 ) -%>
        <td>
          <%- @node.meta_contributions_by_contributor.each do |contributor| -%>
            <p>
              <%= link_to(contributor.fullname, contributor_path(contributor)) %>
              : <%= NodeMetacontribution.contributions_display(contributor.metacontributions).html_safe %>
            </p>
          <%- end -%>
        </td>
        <%- else -%>
        <td>n/a</td>
        <%- end -%>
      </tr>
	  </tbody>
	</table>
  </div>
</div>

<div class="row">
  <div class="span12">
    <h3>Node Event History <%= button_tag("Show &raquo;".html_safe, id: 'infotoggler', class: 'btn btn-small', data: {toggle: 'collapse', target: '#showinfo'}) %></h3>
      <div id="showinfo" class="collapse">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>When</th>
            <th>What</th>
            <th>Who</th>
          </tr>
        </thead>
        <tbody>
          <%- @node.node_activities.order("created_at DESC").each do |ne| -%>
          <tr>
            <td><%= ne.created_at.to_s %></td>
            <td><%= ne.event_to_s %></td>
            <td>
              <%- if(ne.contributor.present?) -%>
              <%= link_to(ne.contributor.fullname, contributor_path(ne.contributor)) %>
              <%- else -%>
              n/a
              <%- end -%>
            </td>
          </tr>
          <%- end -%>
        </tbody>
      </table>
      </div>
  </div>
</div>


<script type="text/javascript">

$('#showinfo').on('show', function () {
  $('#infotoggler').html('Hide &laquo;');
});

$('#showinfo').on('hide', function () {
  $('#infotoggler').html('Show &raquo;');
});

</script>