config/routes.rb
Positronic::Application.routes.draw do
  root :to => 'home#index'
  resources :pages, :only => [:index, :show] do
    member do
      get :traffic_chart
    end
    collection do
      get :panda_impact_summary
      get :totals
      get :aggregate
      post :setdate
      get :comparison_test
      get :graphs
      get :details
      get :overview
      get :publishedcontent
    end
  end

  # data routes
  scope "data" do
    match "/groups", to: "data#groups", :as => 'data_groups'
  end

  resources :contributors, :only => [:show] do
    member do
      get :contributions
      get :metacontributions
    end
  end

  resources :nodes, :only => [:index, :show] do
    collection do
      get :graphs
      get :details
      get :list
    end
  end


  resources :groups, :only => [:index, :show] do
    collection do
      get :list
    end
    member do
      get :pagelist
      get :pages
      get :pagetags
      get :nodes
      get :node_graphs
      get :node_activity
    end
  end


  # aae notice
  match '/aae', to: 'home#aae', :as => 'aae_notice'

  # authentication
  match '/logout', to:'auth#end', :as => 'logout'
  match '/auth/:provider/callback', to: 'auth#success'

  # home routes
  match '/search', to:'home#search', :as => 'search'

  # experiments named routes
  match '/experiments', to: 'experiments#index', :as => 'experiments'

  # catch all
  match '/:controller(/:action(/:id))'

end

app/models/group.rb
# === COPYRIGHT:
#  Copyright (c) North Carolina State University
#  Developed with funding for the National eXtension Initiative.
# === LICENSE:
#
#  see LICENSE file

class Group < ActiveRecord::Base
  extend YearWeek

  EXTENSION_STAFF = 30

  has_many :node_groups
  has_many :nodes, :through => :node_groups
  has_many :node_activities, :through => :nodes
  has_many :tags
  has_many :pages, :through => :tags
  has_many :analytics, :through => :tags
  has_many :page_stats, :through => :tags
  has_many :landing_stats
  has_many :collected_page_stats, :as => :statable

  has_many :contributor_groups
  has_many :contributors, through: :contributor_groups
  has_many :node_contributor_activities, through: :contributors, source: :node_activities


  scope :launched, where(:is_launched => true)

  def self.rebuild
    self.connection.execute("truncate table #{self.table_name};")
    insert_values = []
    PeopleCommunity.where("drupal_node_id IS NOT NULL").each do |group|
      insert_list = []
      insert_list << group.id
      insert_list << group.drupal_node_id
      insert_list << ActiveRecord::Base.quote_value(group.name)
      if(group.publishing_community? and pc = DarmokPublishingCommunity.find_by_id(group.id))
        insert_list << pc.is_launched
      else
        insert_list << 0
      end
      insert_list << ActiveRecord::Base.quote_value(group.created_at.to_s(:db))
      insert_list << ActiveRecord::Base.quote_value(group.updated_at.to_s(:db))
      insert_list << group.publishing_community
      insert_values << "(#{insert_list.join(',')})"
    end
    insert_sql = "INSERT INTO #{self.table_name} VALUES #{insert_values.join(',')};"
    self.connection.execute(insert_sql)
    true
  end

  def self.top_or_bottom_by_metric(top_or_bottom,options = {})
    yearweek = options[:yearweek] || Analytic.latest_yearweek
    pagecount = options[:pagecount] || 10
    limit = options[:limit] || 5
    datatype = options[:datatype] || 'Article'
    metric = options[:metric] || 'unique_pageviews'

    case top_or_bottom
    when 'top'
      sortorder = 'collected_page_stats.per_page DESC'
    when 'bottom'
      sortorder = 'collected_page_stats.per_page ASC,collected_page_stats.pages DESC'
    else
      sortorder = 'collected_page_stats.per_page ASC,collected_page_stats.pages DESC'
    end

    with_scope do
      joins(:collected_page_stats)
      .where("collected_page_stats.datatype = ?",datatype)
      .where("collected_page_stats.metric = ?",metric)
      .where("collected_page_stats.yearweek = ?",yearweek)
      .where("collected_page_stats.pages >= ?",pagecount)
      .order(sortorder).limit(limit)
    end
  end

  def self.top_for_metric(options = {})
    self.top_or_bottom_by_metric('top',options)
  end

  def self.bottom_for_metric(options = {})
    self.top_or_bottom_by_metric('bottom',options)
  end

  def self.top_by_page_average(options = {})
    pagecount = options[:pagecount] || 10
    limit = options[:limit]
    offset = options[:offset]
    datatype = options[:datatype] || 'Article'
    metric = options[:metric] || 'unique_pageviews'
    sortorder = 'collected_page_stats.per_page DESC'


    with_scope do
      scope = joins(:collected_page_stats)
                   .where("collected_page_stats.datatype = ?",datatype)
                   .where("collected_page_stats.metric = ?",metric)
                   .select("#{self.table_name}.*, avg(collected_page_stats.per_page) as per_page_average")
                   .group('groups.id')
                   .order('per_page_average DESC')
      if(limit)
        scope = scope.limit(limit)
      end

      if(offset)
        scope = scope.offset(offset)
      end
      scope
    end
  end



end

app/controllers/groups_controller.rb
# === COPYRIGHT:
#  Copyright (c) North Carolina State University
#  Developed with funding for the National eXtension Initiative.
# === LICENSE:
#
#  see LICENSE file

class GroupsController < ApplicationController

  def index
  end

  def show
    @group = Group.find(params[:id])
    return redirect_to(pages_group_path(@group))
  end

  def list
    @grouplist = Group.order(:name).page(params[:page])
  end


  def pages
    @group = Group.find(params[:id])
    @landing_stats = @group.landing_stats.stats_by_yearweek(@metric)
    @datatype_stats = {}
    @overall_stats = {}
    @comparators = {}
    Page::DATATYPES.each do |datatype|
      @datatype_stats[datatype] = @group.pages.by_datatype(datatype).stats_by_yearweek(@metric)
      @overall_stats[datatype] = Page.by_datatype(datatype).stats_by_yearweek(@metric)
      @comparators[datatype]= YearWeekStatsComparator.new
      @comparators[datatype]["Overall #{datatype.pluralize}"] = @overall_stats[datatype]
      @comparators[datatype]["#{datatype.pluralize}"] = @datatype_stats[datatype]
    end
  end

  def node_activity
    @group = Group.find(params[:id])

    @node_scope = params[:node_scope]
    if(!Node::NODE_SCOPES.include?(@node_scope))
      @node_scope = 'all_nodes'
    end

    @activity = params[:activity]
    if(!NodeActivity::ACTIVITIES.include?(@activity))
      # for now, error later
      @activity =  NodeActivity::ALL_ACTIVITY
    end

    activity_scope =  @group.node_activities.includes(:node,:contributor)
    if(@activity !=  NodeActivity::ALL_ACTIVITY)
      activity_scope = activity_scope.where(activity: @activity)
    end

    @node_activity = activity_scope.order('created_at DESC').page(params[:page])
  end

  def node_graphs
    @group = Group.find(params[:id])

    @node_scope = params[:node_scope]
    if(!Node::NODE_SCOPES.include?(@node_scope))
      @node_scope = 'all_nodes'
    end

    @activity = params[:activity]
    if(!NodeActivity::ACTIVITIES.include?(@activity))
      # for now, error later
      @activity =  NodeActivity::ALL_ACTIVITY
    end
  end


def nodes
  @group = Group.find(params[:id])

  @activity = params[:activity]
  if(!NodeActivity::ACTIVITIES.include?(@activity))
    # for now, error later
    @activity =  NodeActivity::ALL_ACTIVITY
  end

  # this is a crapton of stats
  @overall_everything_stats = @group.nodes.overall_stats(@activity)
  @lastweek_everything_stats = @group.nodes.latest_activity.overall_stats(@activity)
  @everything_stats_by_week = @group.nodes.stats_by_yearweek(@activity)

  @overall_publishable_stats = YearWeekStatsComparator.new
  @lastweek_publishable_stats = YearWeekStatsComparator.new
  @publishable_stats_by_week = YearWeekStatsComparator.new
  Node::PUBLISHED_NODE_SCOPES.each do |node_scope|
    @overall_publishable_stats[node_scope] = @group.nodes.send(node_scope).overall_stats(@activity)
    @lastweek_publishable_stats[node_scope] = @group.nodes.send(node_scope).latest_activity.overall_stats(@activity)
    @publishable_stats_by_week[node_scope] = @group.nodes.send(node_scope).stats_by_yearweek(@activity)
  end

  @overall_administrative_stats = YearWeekStatsComparator.new
  @lastweek_administrative_stats = YearWeekStatsComparator.new
  @administrative_stats_by_week = YearWeekStatsComparator.new
  Node::ADMINISTRATIVE_NODE_SCOPES.each do |node_scope|
    @overall_administrative_stats[node_scope] = @group.nodes.send(node_scope).overall_stats(@activity)
    @lastweek_administrative_stats[node_scope] = @group.nodes.send(node_scope).latest_activity.overall_stats(@activity)
    @administrative_stats_by_week[node_scope] = @group.nodes.send(node_scope).stats_by_yearweek(@activity)
  end

end


  def pagelist
    @group = Group.find(params[:id])
    @scope = @group.pages

    @datatype = params[:datatype]
    if(!Page::DATATYPES.include?(@datatype))
      @datatype = nil
    else
      @scope = @scope.by_datatype(@datatype)
    end
    @pagelist = @scope.filtered_pagelist(params).page(params[:page])


    list_type = @datatype.nil? ? 'Pages' : @datatype.pluralize
    case(params[:filter])
    when 'viewed'
      @page_title = "Viewed #{list_type} for Group ##{@group.id}"
      @page_title_display = "Viewed #{list_type} for #{@group.name}"
      @endpoint = "Viewed #{@datatype.pluralize}"
    when 'unviewed'
      @page_title = "Unviewed #{list_type} for Group ##{@group.id}"
      @page_title_display = "Unviewed #{list_type} for #{@group.name}"
      @endpoint = "Unviewed #{@datatype.pluralize}"
    else
      @page_title = "All #{list_type}"
      @page_title_display = "All #{list_type}"
      @endpoint = "All #{@datatype.pluralize}"
    end

  end

  def pagetags
    @group = Group.find(params[:id])
    @tagslist = Tag.pagetags_for_group(@group).order(:name).uniq
    @tagcounts = Tag.pagetags_for_group(@group).group('tags.id').count('tags.id')

  end

end

app/helpers/groups_helper.rb
# encoding: utf-8
# === COPYRIGHT:
# Copyright (c) 2014 North Carolina State University
# === LICENSE:
# see LICENSE file

module GroupsHelper


  def groups_node_activity_graph_nav_li(activity)
    listclass = 'active' if activity == @activity
    if(activity == NodeActivity::ALL_ACTIVITY)
      label = 'All'
    else
      label = activity.pluralize.capitalize
    end
    nav_li = '<li'
    if(listclass.present?)
      nav_li += " class=#{listclass}"
    end
    nav_li += '>'
    nav_li += link_to(label,node_graphs_group_path(id: @group.id, node_scope: @node_scope, activity: activity))
    nav_li += '</li>'
    nav_li.html_safe
  end


  def groups_node_activity_list_nav_li(activity)
    listclass = 'active' if activity == @activity
    if(activity == NodeActivity::ALL_ACTIVITY)
      label = 'All'
    else
      label = activity.pluralize.capitalize
    end
    nav_li = '<li'
    if(listclass.present?)
      nav_li += " class=#{listclass}"
    end
    nav_li += '>'
    nav_li += link_to(label,node_activity_group_path(id: @group.id, node_scope: @node_scope, activity: activity))
    nav_li += '</li>'
    nav_li.html_safe
  end

end

app/views/groups/_group_breadcrumbs.html.erb
<%- # TODO: there have to be better ways of doing this that utilize the action names -%>
<ul class="breadcrumb">
  <li>
    <%- if local_assigns.has_key?(:endpoint) and endpoint == 'Groups' -%>
      Groups<span class="divider">/</span>
    <%- else -%>
      <%= link_to('Groups',groups_path) %><span class="divider">/</span>
    <%- end -%>
  </li>
  <%- if @group -%>
    <%- if params[:action] == 'show' %>
      <li class="active"><%= @group.name %></li>
    <%- else -%>
      <li><%= link_to(@group.name, group_path(@group)) %><span class="divider">/</span></li>
    <%- end -%>
  <%- end -%>
  <%- if local_assigns.has_key?(:endpoint) and endpoint != 'Groups'-%>
    <li class='active'><%= endpoint %></li>
  <%- end -%>
</ul>

app/views/groups/index.html.erb
<% @page_title = "Groups page information" %>
<%= render(:partial => 'group_breadcrumbs', :locals => {:endpoint => 'Groups'}) %>
<header class="jumbotron subhead" id="overview">
  <h1><%= @page_title %></h1>
  <p class="lead">Data for <%= year_week_for_last_week%> (<%= date_range_for_last_week%>) </p>

</header>


<div class="well">
  <p><%= text_field_tag("groupfinder",'',{:class => 'input search-query span4', :placeholder => 'Type and select to jump to group'}) %>
  <script class="code" type="text/javascript">
    $('#groupfinder').autocomplete({
      source: "/data/groups",
      minLength: 2,
      select: function(event, ui) {
        window.location = '/groups/' + ui.item.id
      }
    });
  </script>
  or <%= link_to('Browse all groups', list_groups_path) %></p>
</div>


<div class="page-header">
  <h2>Top Groups for Week <small>by average views/page</small></h2>
</div>

<div class="row">
  <%- Page::DATATYPES.each do |datatype| -%>
    <div class="span4">
      <div class="page-header">
        <h3><%= datatype.pluralize%></h3>
      </div>
      <%- groupslist = Group.launched.top_for_metric(metric: 'unique_pageviews', datatype: datatype) -%>
      <dl>
      <%- groupslist.each do |group| %>
        <%- group_stats = group.pages.by_datatype(datatype).stats_by_yearweek('unique_pageviews') -%>
        <dt><%= link_to(group.name, group_path(group))%></dt>
        <dd><span class='regnumber'><%= number_with_precision(group_stats[@latest_yearweek]['per_page'], :precision => 2) %></span> views</dd>
        <dd><span class='regnumber'><%= seen_pct(group_stats[@latest_yearweek]) %></span>
        of <span class='regnumber'><%= number_with_delimiter(group_stats[@latest_yearweek]['pages'])%></span> items viewed</dd>
      <%- end -%>
      </dl>
    </div>
  <%- end -%>
</div>

app/views/groups/list.html.erb
<% @page_title = "Browse Groups" %>
<%= render(:partial => 'group_breadcrumbs', :locals => {:endpoint => 'List'}) %>
<header class="jumbotron subhead" id="overview">
  <h1><%= @page_title %></h1>
</header>

<div class="row">
  <div class="span12">
      <%= paginate(@grouplist) %>
  <table class="table table-bordered">

    <thead>
      <tr>
        <th>Group</th>
        <th>Page Activity</th>
        <th>Node Activity</th>
      </tr>
    </thead>

    <tbody>
      <%- @grouplist.each do |group| -%>
      <tr>
        <td><%= group.name %></td>
        <td><%= link_to('Page Activity',pages_group_path(group)) %></td>
        <td><%= link_to('Node Activity',nodes_group_path(group)) %></td>
      </tr>
      <%- end -%>
    </tbody>
  </table>
  </div>

app/views/groups/node_activity.html.erb
<%-  @page_title = "#{node_scope_label(@node_scope)} Activity for Group ##{@group.id}" -%>
<header class="jumbotron subhead" id="overview">
  <h1><%= "#{node_scope_label(@node_scope)} Activity for #{@group.name}" %></h1>
  <p class="lead">Data for <%= year_week_for_last_week%> (<%= date_range_for_last_week%>) </p>
</header>

<ul class="nav nav-tabs">
  <%- NodeActivity::ACTIVITIES.each do |activity| -%>
  <%= groups_node_activity_list_nav_li(activity) %>
  <%- end -%>
</ul>


<div class="row">
  <div class="span12">
      <%= paginate(@node_activity) %>
  <table class="table table-bordered">

    <thead>
      <tr>
        <th>Node</th>
        <th>Contributor</th>
        <th>Type</th>
        <th>Activity</th>
        <th>When</th>
      </tr>
    </thead>

    <tbody>
      <%- @node_activity.each do |na| -%>
      <tr>
        <td><%= node_title_display(na.node) %></td>
        <td><%= link_to(na.contributor.fullname, contributor_path(na.contributor))  %></td>
        <td><%= na.node.node_type %></td>
        <td><%= NodeActivity.event_to_s(na.event) %></td>
        <td><%= na.created_at.to_s %></td>
      </tr>
      <%- end -%>
    </tbody>
  </table>
  </div>

app/views/groups/node_graphs.html.erb
<%-  @page_title = "#{node_scope_label(@node_scope)} Activity Graphs for Group ##{@group.id}" -%>
<header class="jumbotron subhead" id="overview">
  <h1><%= "#{node_scope_label(@node_scope)} Activity Graphs for #{@group.name}" %></h1>
  <p class="lead">Data for <%= year_week_for_last_week%> (<%= date_range_for_last_week%>) </p>
</header>

<ul class="nav nav-tabs">
  <%- NodeActivity::ACTIVITIES.each do |activity| -%>
  <%= groups_node_activity_graph_nav_li(activity) %>
  <%- end -%>
</ul>

<%= link_to("<i class='icon-th'></i>Details".html_safe,node_activity_group_path(id: @group.id, node_scope: @node_scope, activity: @activity),:class => 'btn') %>



<%- ['contributions','items','contributors'].each do |metric| -%>
<div class="page-header">
  <h1><%= activity_scope_label(@activity) %> - <%= metric.capitalize %></h1>
</div>
<div class="row">
  <div class="span12">
    <%= render(:partial => 'shared/line_plot', :locals => {:data => @group.nodes.send(@node_scope).stats_by_yearweek(@activity).to_graph_data(metric.to_sym), :datalabel => metric })%>
  </div>
</div>
<%- end -%>

app/views/groups/nodes.html.erb
<% @page_title = "Node Activity Information" %>

<header class="jumbotron subhead" id="overview">
  <h1><%= @page_title %></h1>
  <p class="lead">Data for <%= year_week_for_last_week%> (<%= date_range_for_last_week%>)</p>
</header>


  <div class="page-header">
    <h2>All Nodes</h2>
  </div>
  <div class="row">
    <div class="span4">
      <h3>Overall</h3>
      <%= c_i_c_text(@overall_everything_stats) %>

      <h3>Last Week</h3>
      <%= c_i_c_text(@lastweek_everything_stats) %>

    </div>

    <div class="span8">
      <h3>Contributors per week over time <small><%= link_to('more graphs...',node_graphs_group_path(@group))%></small></h3>
      <%= render(:partial => 'shared/line_plot', :locals => {:data => @everything_stats_by_week.to_graph_data(:contributors), :datalabel => 'all_contributors' })%>
    </div>
  </div>

  <div class="page-header">
    <h2>Publishable Documents</h2>
  </div>
  <div class="row">
  <%- Node::PUBLISHED_NODE_SCOPES.each do |node_scope| -%>

    <div class="span4">
      <h3><%= node_scope.capitalize %> </h3>
      <hr/>
      <h4>Overall</h4>
      <%= c_i_c_text(@overall_publishable_stats[node_scope]) %>

      <h4>Last Week</h4>
      <%= c_i_c_text(@lastweek_publishable_stats[node_scope])  %>

    </div>
  <%- end -%>
  </div>

  <div class="row">
  <div class="span12">
    <h3>Contributors By Week</h3>
    <%= render(:partial => 'shared/comparison_plot',
               :locals => {data: @publishable_stats_by_week.to_graph_data(:contributors),
                           labels: @publishable_stats_by_week.to_graph_labels.map{|l| l.capitalize},
                           datalabel: "publishable_contributors" }) -%>
  </div>
  </div>

  <div class="page-header">
    <h2>Administrative Documents</h2>
  </div>
  <div class="row">
  <%- Node::ADMINISTRATIVE_NODE_SCOPES.each do |node_scope| -%>

    <div class="span3">
      <h3><%= Node::ADMINISTRATIVE_NODE_SCOPES_LABELS[node_scope] %></h3>
      <hr/>
      <h4>Overall</h4>
      <%= c_i_c_text(@overall_administrative_stats[node_scope]) %>

      <h4>Last Week</h4>
      <%= c_i_c_text(@lastweek_administrative_stats[node_scope])  %>

    </div>
  <%- end -%>
  </div>

  <div class="row">
  <div class="span12">
    <h3>Contributors By Week</h3>
    <%= render(:partial => 'shared/comparison_plot',
               :locals => {data: @administrative_stats_by_week.to_graph_data(:contributors),
                           labels: @administrative_stats_by_week.to_graph_labels.map{|l| Node::ADMINISTRATIVE_NODE_SCOPES_LABELS[l]},
                           datalabel: "administrative_contributors" }) -%>
  </div>
  </div>

app/views/groups/pagelist.html.erb
<%= render(:partial => 'group_breadcrumbs', :locals => {:showgroups=> true, :endpoint => @endpoint}) %>
<header class="jumbotron subhead" id="overview">
  <h1><%= @page_title_display.html_safe %></h1>
  <p class="lead">Data for <%= year_week_for_last_week%> (<%= date_range_for_last_week%>) </p>
</header>

<div class="row">
  <div class="span12">
    <%= paginate(@pagelist) %>
    <%= render(:partial => 'shared/pagelist', :locals => {:pagelist => @pagelist} )%>
  </div>
</div>

app/views/groups/pages.html.erb
<% @page_title = "Page Information - Group ##{@group.id}" %>
<%= render(:partial => 'group_breadcrumbs', :locals => {group: @group, endpoint: 'Pages'}) %>
<header class="jumbotron subhead" id="overview">
  <h1>Page Information for <%= @group.name %></h1>
  <p class="lead">
    Data for <%= year_week_for_last_week%>
    (<%= date_range_for_last_week%>)
  </p>
</header>

<div class="page-header">
  <h2>Overall</h2>
</div>

<div class="row">
  <div class="span8">
    <h3>Landing Page Views</h3>
    <%= render(:partial => 'shared/line_plot', :locals => {:data => @landing_stats.to_graph_data('total'), :datalabel => 'index'})%>
  </div>

  <div class="span4">
    <h3>Landing Page Stats</h3>
    <p><span class='bignumber'><%=number_with_precision(@landing_stats[@latest_yearweek]['total'], :precision => 0)%></span> views for week</p>
    <p><%= pct_change(@landing_stats[@latest_yearweek]['pct_change_week'],'mednumber') %> from previous week</p>
    <p><%= pct_change(@landing_stats[@latest_yearweek]['pct_change_year'],'mednumber') %> from previous year</p>
  </div>
</div>

<div class="row">
  <%- Page::DATATYPES.each do |datatype| -%>
    <div class="span4">
      <%- if @datatype_stats[datatype][@latest_yearweek] -%>
        <h3><%= datatype.pluralize %>
          <span><%= link_to("details &raquo;".html_safe,details_pages_path(group_id: @group.id,datatype: datatype),:class => 'btn btn-small') %></span>
        </h3>
        <%= render(:partial => 'shared/overall_views_information',
                   :locals => {:datatype => datatype, :stats_for_week => @datatype_stats[datatype][@latest_yearweek]}) %>
     <%- else -%>
       <h3><%= datatype.pluralize %></h3>
       <p> No Data </p>
     <%- end -%>
    </div>
  <%- end -%>
</div>

<%- ['Article', 'Faq'].each do |datatype| -%>
<div class="row">
  <div class="span12">
    <h3><%= "#{datatype} Views vs. Overall average" %></h3>
    <%= render(:partial => 'shared/comparison_plot',
               :locals => {data: @comparators[datatype].to_graph_data('per_page'),
                           labels: @comparators[datatype].to_graph_labels,
                           datalabel: "per_page_#{datatype}" }) -%>
  </div>
</div>

<div class="row">
  <div class="span12">
    <h3><%= "#{datatype} % Viewed vs. Overall average" %></h3>
    <%= render(:partial => 'shared/comparison_plot',
               :locals => {data: @comparators[datatype].to_graph_data('seen',{relative_to: 'pages', relative_percentage: true}),
                           labels: @comparators[datatype].to_graph_labels,
                           datalabel: "seen_pct_#{datatype}",
                           ymax: 100 }) -%>
  </div>
</div>
<%- end -%>

app/views/groups/pagetags.html.erb
<% @page_title = "Page Tags for Group ##{@group.id}" %>
<%= render(:partial => 'group_breadcrumbs', :locals => {:endpoint => "Page Tags"}) %>
<header class="jumbotron subhead" id="overview">
  <h1><%= @page_title %></h1>
  <p class="lead">Data for <%= year_week_for_last_week%> (<%= date_range_for_last_week%>) </p>
</header>

<div class="row">
  <div class="span12">
    <table class="table tablesorter tablesorter-blue">
      <thead>
        <th>Tag</th>
        <th>Count</th>
      <tbody>
        <%- @tagslist.each do |tag| -%>
        <tr>
          <td><%= link_to(tag.name,overview_pages_path(tag: tag.name)) %></td>
          <td><%= @tagcounts[tag.id] %></td>
        </tr>
        <%- end -%>
      </tbody>
  </table>
 </div>

app/views/groups/show.html.erb
<% @page_title = "Data for #{@group.name}" %>
<%= render(:partial => 'group_breadcrumbs', :locals => {:group => @group}) %>
<header class="jumbotron subhead" id="overview">
  <h1><%= @group.name %></h1>
  <p class="lead">
    Data for <%= year_week_for_last_week%>
    (<%= date_range_for_last_week%>)
  </p>
</header>




<div class="row">

  <div class="span6">
    <h2>Pages</h2>
    <p><%= link_to("Explore &raquo;".html_safe,pages_group_path(@group),:class => 'btn btn-small btn-info') %></p>
  </div>


<!--   <div class="span6">
    <h2>Nodes</h2>
    <p><a class="btn" href="#">Explore &raquo;</a></p>
  </div> -->

</div