config/routes.rb
Positronic::Application.routes.draw do
  root :to => 'home#index'
  resources :pages, :only => [:index, :show] do
    member do
      get :traffic_chart
    end
    collection do
      get :panda_impact_summary
      get :totals
      get :aggregate
      post :setdate
      get :comparison_test
      get :graphs
      get :details
      get :overview
      get :publishedcontent
    end
  end

  # data routes
  scope "data" do
    match "/groups", to: "data#groups", :as => 'data_groups'
  end

  resources :contributors, :only => [:show] do
    member do
      get :contributions
      get :metacontributions
    end
  end

  resources :nodes, :only => [:index, :show] do
    collection do
      get :graphs
      get :details
      get :list
    end
  end


  resources :groups, :only => [:index, :show] do
    collection do
      get :list
    end
    member do
      get :pagelist
      get :pages
      get :pagetags
      get :nodes
      get :node_graphs
      get :node_activity
    end
  end


  # aae notice
  match '/aae', to: 'home#aae', :as => 'aae_notice'

  # authentication
  match '/logout', to:'auth#end', :as => 'logout'
  match '/auth/:provider/callback', to: 'auth#success'

  # home routes
  match '/search', to:'home#search', :as => 'search'

  # experiments named routes
  match '/experiments', to: 'experiments#index', :as => 'experiments'

  # catch all
  match '/:controller(/:action(/:id))'

end

app/views/shared/_bar_chart.html.erb
  <div id="plot_for_<%= datalabel %>" class='barchart'></div>
  <script class="code" type="text/javascript">
    $(document).ready(function(){
      setTimeout(function(){
      var data = <%= data.to_json.html_safe -%>;
      var labels = <%= labels.to_json.html_safe -%>;
      var plot1 = jQuery.jqplot("plot_for_<%= datalabel %>", [data],
        {
          series:[{renderer:$.jqplot.BarRenderer}],
          axesDefaults: {

          },
          axes: {
            xaxis: {
              <%- if data.size >= 7 -%>
              tickRenderer: $.jqplot.CanvasAxisTickRenderer,
              tickOptions: {
               angle: -30
              },
              <%- end -%>
              renderer: $.jqplot.CategoryAxisRenderer,
              ticks: labels
            },
            yaxis:{padMax:1.3}
          },
          seriesDefaults: {
            renderer:$.jqplot.BarRenderer,
            rendererOptions: {
              fillToZero: true 
            },
            pointLabels: { show: true },            
          },
          grid: {
              drawBorder: false,
              shadow: false,
              background: "white"
          }
        }
      );
    });
  });
  </script>

app/views/shared/_comparison_plot.html.erb
  <div id="comparison_plot_for_<%= datalabel %>"></div>
  <script class="code" type="text/javascript">
    $(document).ready(function(){
      setTimeout(function(){
      var data = <%= data.to_json.html_safe %>;
      var labels = <%= labels.to_json.html_safe %>;
      var plot1 = jQuery.jqplot("comparison_plot_for_<%= datalabel %>", data,
        {
          axesDefaults: {
            pad: 0
          },
          axes: {
            xaxis: {
              renderer: $.jqplot.DateAxisRenderer,
              tickOptions:{
                formatString:'%b&nbsp;%d&nbsp;%Y'
              }
            },
            yaxis: {
              min: 0,
              <%- if local_assigns.has_key?(:ymax) -%>
              max: <%= ymax %>,
              <%- end -%>
              tickOptions:{
               formatString:'%.1f'
              },   
            }
          },
          seriesDefaults: {
            showMarker: false,
            shadow: false
          },
          legend: {
              show: true,
              renderer: $.jqplot.EnhancedLegendRenderer,
              placement: "outsideGrid",
              labels: labels,
              location: "ne",
              rowSpacing: "2px",
              border: "0px",
              rendererOptions: {
                  // set to true to replot when toggling series on/off
                  // set to an options object to pass in replot options.
                  seriesToggle: 'normal',
                  seriesToggleReplot: {resetAxes: true},
                  <%- if local_assigns.has_key?(:legend_columns) -%>
                  numberColumns: <%= legend_columns %>,
                  <%- end -%>
              }
          },
          grid: {
              drawBorder: false,
              shadow: false,
              background: "white"
          },
          highlighter: {
            show: true,
            sizeAdjust: 7.5
          },
          cursor: {
            show: true,
            zoom: true,
            showTooltip: false,
          }
        }
      );
    }, 100);
    });
  </script>

app/views/shared/_flashmessages.html.erb
<%- flash.each do |type,message| -%>
  <div class='<%= twitter_alert_class(type) %>'>
    <a class='close' data-dismiss="alert" href='#'>×</a>
    <p><%= message %></p>
  </div>
<%- end -%>

app/views/shared/_google_tracking.html.erb
<%-
  case Settings.app_location
      when 'production'   then @gaprofile = "UA-155321-48"
      when 'demo'         then @gaprofile = "UA-155321-0"
      when 'localdev'     then @gaprofile = "UA-155321-0"
      else                     @gaprofile = "UA-155321-0"
  end
-%>

<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', '<%= @gaprofile %>']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/shared/_line_plot.html.erb
  <div id="plot_for_<%= datalabel %>"></div>
  <script class="code" type="text/javascript">
    $(document).ready(function(){
      setTimeout(function(){
      var data = <%= data.to_json.html_safe %>;
      var plot1 = jQuery.jqplot("plot_for_<%= datalabel %>", data,
        {
          axesDefaults: {
            pad: 0
          },
          axes: {
            xaxis: {
              renderer: $.jqplot.DateAxisRenderer,
              tickOptions:{
               formatString:'%b&nbsp;%d&nbsp;%Y'
              }
            },
            yaxis: {
              <%- if datalabel != 'change' -%>
              min: 0,
              <%- end -%>
              <%- if local_assigns.has_key?(:ymax) -%>
              max: <%= ymax %>,
              <%- end -%>
              tickOptions:{
               formatString:'%.1f'
              },              
            }
          },
          seriesDefaults: {
            <%- if local_assigns.has_key?(:fill) and fill == true -%>
            fill: true,
            <%- end -%>
            showMarker: false,
            shadow: false
          },
          grid: {
              drawBorder: false,
              shadow: false,
              background: "white"
          },
          highlighter: {
            show: true,
            sizeAdjust: 7.5
          },
          cursor: {
            show: true,
            zoom: true,
            showTooltip: false,
          }
        }
      );
    }, 100);
    });
  </script>

app/views/shared/_navbar.html.erb
<ul class="nav">
	<%= link_to("eXtension Data",root_path,:class=>'brand')%>
</ul>

<!-- Core Navigation -->
<%- if !@hide_navbar%>
<ul class="nav">
	<%= nav_item(pages_path,'Pages') %>
	<%= nav_item(nodes_path,'Nodes') %>
	<%= nav_item(groups_path,'Groups') %>
	<%= nav_item(aae_notice_path,'Ask an Expert') %>
	<%= nav_item(experiments_path,'Experiments') %>
	<%= nav_item(search_path,'Search') %>
</ul>


<!-- right pulldown -->
<ul class="nav pull-right">
	<%- if @currentcontributor -%>
	<li class="dropdown">
		<a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= @currentcontributor.fullname %><b class="caret"></b></a>
		<ul class="dropdown-menu">
			<%= nav_item(contributor_path(@currentcontributor),'Your Contributions') %>
			<li class="divider"></li>
			<%= nav_item(logout_path,'Sign out') %>
		</ul>
	</li>
	<%- else -%>
		<%= nav_item('/auth/extension','Sign in (eXtensionID)') %>
	<%- end -%>
</ul>
<%- end -%>

app/views/shared/_overall_views_information.html.erb
<%-
  pages = (stats_for_week['pages'] || 0)
  seen = (stats_for_week['seen'] || 0)
  views = (stats_for_week['per_page'] || 0)
  if(pages > 0)
    seen_pct = ((seen/pages)*100).to_f
  else
    seen_pct = 0
  end
-%>

<p><span class='mednumber'><%= number_with_delimiter(pages)%></span> pages</p>
<p><span class='mednumber'><%=number_with_precision(views, :precision => 2)%></span> views/page for week</p>
<p><span class='mednumber'><%=number_to_percentage(seen_pct, :precision => 2)%></span> viewed for week</p>
<p><%= pct_change(stats_for_week['pct_change_week'],'mednumber') %> from previous week</p>
<p><%= pct_change(stats_for_week['pct_change_year'],'mednumber') %> from previous year</p>

app/views/shared/_pagelist.html.erb
<table class="table table-bordered table-striped">
  <thead>
    <tr>
        <th>Page</th>
        <th>Weeks Published</th>
        <th>Total Views</th>
        <th>Average Views</th>
        <th>This Week</th>
        <th>% Change Week</th>
        <th>% Change Year</th>
    </tr>
  </thead>

  <tbody>
    <%- for page in pagelist -%>
  	<tr>
      <%- if page.title.blank?
          title = '(blank)'
        else
          title = page.title.truncate(80, :separator => ' ')
        end -%>
      <td><%= link_to(title,page_path(page)) %></td>
      <td><%= page.eligible_weeks %></td>
      <td><%= page.try(:total) %></td>
      <td><%= page.try(:mean) %></td>
      <td><%= page.try(:this_week) %></td>
      <td><%= pct_change(page.pct_change_week)%></td>
      <td><%= pct_change(page.pct_change_year)%></td>
    </tr>
  <%- end -%>
  </tbody>
</table>

app/views/shared/_percentiles_plot.html.erb
  <div id="plot_for_percentiles"></div> 
  <script class="code" type="text/javascript">
    $(document).ready(function(){
      setTimeout(function(){
      var data = <%= data.to_json.html_safe %>;
      var labels = <%= labels.to_json.html_safe %>;
      var plot1 = jQuery.jqplot("plot_for_percentiles", data, 
        {
          axesDefaults: {
            pad: 0
          },
          axes: {
            xaxis: {
              renderer: $.jqplot.DateAxisRenderer,
              tickOptions:{
                formatString:'%b&nbsp;%d&nbsp;%Y'
              }
            },
            yaxis: {
              min: 0,
            } 
          },
          seriesDefaults: {
            showMarker: false,
            shadow: false
          },
          legend: {
              show: true,
              renderer: $.jqplot.EnhancedLegendRenderer,
              placement: "outsideGrid",
              labels: labels,
              location: "ne",
              rowSpacing: "2px",
              border: "0px",
              rendererOptions: {
                  // set to true to replot when toggling series on/off
                  // set to an options object to pass in replot options.
                  seriesToggle: 'normal',
                  seriesToggleReplot: {resetAxes: true}
              }
          },
          grid: {
              drawBorder: false,
              shadow: false,
              background: "white"
          },
          cursor: {
            show: true,
            zoom: true,
          }
        }
      );
    }, 100);
    });
  </script>

app/views/shared/_scatter_plot.html.erb
  <div id="plot_for_<%= datalabel %>"></div>
  <script class="code" type="text/javascript">
    $(document).ready(function(){
      setTimeout(function(){
      var data = <%= data.to_json.html_safe %>;
      var plot1 = jQuery.jqplot("plot_for_<%= datalabel %>", data,
        {
          axesDefaults: {
            pad: 0,
          },
          axes: {
            xaxis: {
              label: '<%= xlabel %>',
            },
            yaxis: {
              label: '<%= ylabel %>',
              <%- if datalabel != 'change' -%>
              min: 0,
              <%- end -%>
              <%- if local_assigns.has_key?(:ymax) -%>
              max: <%= ymax %>,
              <%- end -%>
            }
          },
          seriesDefaults: {
            <%- if local_assigns.has_key?(:fill) and fill == true -%>
            fill: true,
            <%- end -%>
            showMarker: true,
            shadow: false,
            showLine: false,
            markerOptions: {
              <%- if local_assigns.has_key?(:pointsize) -%>
              size: <%= pointsize %>,
              <%- end -%>
            },
          },
          grid: {
              drawBorder: false,
              shadow: false,
              background: "white"
          },
          cursor: {
            show: true,
            zoom: true,
            showTooltip: false,
          }
        }
      );
    }, 100);
    });
  </script>