config/routes.rb
Positronic::Application.routes.draw do
  root :to => 'home#index'
  resources :pages, :only => [:index, :show] do
    member do
      get :traffic_chart
    end
    collection do
      get :panda_impact_summary
      get :totals
      get :aggregate
      post :setdate
      get :comparison_test
      get :graphs
      get :details
      get :overview
      get :publishedcontent
    end
  end

  # data routes
  scope "data" do
    match "/groups", to: "data#groups", :as => 'data_groups'
  end

  resources :contributors, :only => [:show] do
    member do
      get :contributions
      get :metacontributions
    end
  end

  resources :nodes, :only => [:index, :show] do
    collection do
      get :graphs
      get :details
      get :list
    end
  end


  resources :groups, :only => [:index, :show] do
    collection do
      get :list
    end
    member do
      get :pagelist
      get :pages
      get :pagetags
      get :nodes
      get :node_graphs
      get :node_activity
    end
  end


  # aae notice
  match '/aae', to: 'home#aae', :as => 'aae_notice'

  # authentication
  match '/logout', to:'auth#end', :as => 'logout'
  match '/auth/:provider/callback', to: 'auth#success'

  # home routes
  match '/search', to:'home#search', :as => 'search'

  # experiments named routes
  match '/experiments', to: 'experiments#index', :as => 'experiments'

  # catch all
  match '/:controller(/:action(/:id))'

end

app/views/pages/_contributor_page_breadcrumbs.html.erb
<%- # TODO: there have to be better ways of doing this that utilize the action names -%>
<ul class="breadcrumb">
  <li>Contributors<span class="divider">/</span></li>
  <li><%= link_to(@contributor.fullname, contributor_path(@contributor)) %><span class="divider">/</span></li>

  <%- if @datatype and (!local_assigns.has_key?(:endpoint) or endpoint != @datatype.pluralize) -%>
  <li><%= link_to("#{@datatype.pluralize}",details_pages_path(datatype: @datatype, contributor_id: @contributor.id)) %><span class="divider">/</span></li>
  <%- end -%>

  <%- if local_assigns.has_key?(:endpoint) and endpoint != 'Pages'-%>
  <li class='active'><%= endpoint %></li>
  <%- end -%>
</ul>

app/views/pages/_page_breadcrumbs.html.erb
<%- # TODO: there have to be better ways of doing this that utilize the action names -%>
<ul class="breadcrumb">
  <li>
    <%- if local_assigns.has_key?(:endpoint) and endpoint == 'Pages' -%>
      Pages<span class="divider">/</span>
    <%- else -%>
      <%= link_to('Pages',pages_path) %><span class="divider">/</span>
    <%- end -%>
  </li>

  <%- if @datatype and (!local_assigns.has_key?(:endpoint) or endpoint != @datatype.pluralize) -%>
  <li><%= link_to(@datatype.pluralize,details_pages_path(datatype: @datatype)) %><span class="divider">/</span></li>
  <%- end -%>
  
  <%- if local_assigns.has_key?(:endpoint) and endpoint != 'Pages'-%>
  <li class='active'><%= endpoint %></li>
  <%- end -%>
</ul>

app/views/pages/_page_information_table.html.erb
<table class="table table-bordered">

  <tbody>
    <tr>
      <td>Groups</td>
      <td><%= @page.groups.map{|g| link_to(g.name, group_path(g))}.join(', ').html_safe %></td>
    </tr>
    <tr>
    <tr>
      <td>Page Type</td>
      <td><%= @page.datatype %></td>
    </tr>
    <tr>
      <td>Index status</td>
      <td>
      <%- if @page.indexed == 1 -%>
        Indexed. Page can be indexed by all search engines.
      <%- elsif @page.indexed == 2 -%>
        Google asked to not index. Page can be indexed by other search engines.
      <%- else -%>
        All search engines asked to not index.
      <%- end -%>
      </td>
    </tr>
    <tr>
      <td>Words</td>
      <td><%= number_with_delimiter(@page.content_words) %></td>
    </tr>
    <tr>
      <td>Source Published At</td>
      <td><%= @page.source_created_at %></td>
    </tr>
    <tr>
      <td>Source Updated At</td>
      <td><%= @page.source_updated_at %></td>
    </tr>
    <%- if(!@page.node.nil?) -%>
    <tr>
      <td>Contributors</td>
      <td>
        <%- @page.node.contributions_by_contributor.each do |contributor| -%>
          <p>
            <%= link_to(contributor.fullname, contributor_path(contributor)) %>
            : <%= NodeActivity.contributions_display(contributor.contributions).html_safe %>
          </p>
        <%- end -%>
      </td>
    </tr>
    <%- meta_activity_counts = @page.node.metacontributions_count -%>
    <tr>
      <td>Listed contributors</td>
      <%- if(meta_activity_counts[:contributors] > 0 ) -%>
      <td>
        <%- @page.node.meta_contributions_by_contributor.each do |contributor| -%>
          <p>
            <%= link_to(contributor.fullname, contributor_path(contributor)) %>
            : <%= NodeMetacontribution.contributions_display(contributor.metacontributions).html_safe %>
          </p>
        <%- end -%>
      </td>
      <%- else -%>
      <td>n/a</td>
      <%- end -%>
    </tr>
    <%- end -%>
  </tbody>
</table>

app/views/pages/aggregate.html.erb
<%- if @group -%>
  <%= render(:partial => 'group_page_breadcrumbs', :locals => {:endpoint => @endpoint}) %>
<%- else -%>
  <%= render(:partial => 'page_breadcrumbs', :locals => {:endpoint => @endpoint}) %>
<%- end -%>
<header class="jumbotron subhead" id="overview">
  <h1><%= @page_title_display.html_safe %></h1>
  <p class="lead">Data for <%= year_week_for_last_week%> (<%= date_range_for_last_week%>)
    <%- link_params = params.merge({download: 'csv'}) -%>
    <span class='pull-right'><%= link_to("<i class='icon-file'></i>Download (.csv)".html_safe,link_params,:class => 'btn') %></span></p>
</header>

<div class="row">
  <div class="span12">
    <%= paginate(@statlist) %>

    <table class="table table-bordered table-striped sortable">
      <thead>
        <tr>
            <%= sortable_th(column: 'yearweek', title: 'YearWeek', direction: 'asc') %>
            <%= sortable_th(column: 'yearweek_date', title: 'YearWeek Date', direction: 'asc') %>
            <%= sortable_th(column: 'pages', title: 'Pages', direction: 'desc') %>
            <%= sortable_th(column: 'seen', title: 'Seen', direction: 'desc') %>
            <%= sortable_th(column: 'seen_pct', title: '% Seen', direction: 'desc') %>
            <%= sortable_th(column: 'total', title: 'Total', direction: 'desc') %>
            <%= sortable_th(column: 'per_page', title: 'Per Page', direction: 'desc') %>
            <%- Settings.display_percentiles.each do |pct| -%>
              <%= sortable_th(column: "pct_#{pct}", title: "#{pct}th", direction: 'desc') %>
            <%- end -%>
        </tr>
      </thead>

      <tbody>
        <%- for stat in @statlist -%>
        <tr>
          <td><%= stat.yearweek %></td>
          <td><%= stat.yearweek_date %></td>
          <td><%= stat.pages %></td>
          <td><%= stat.seen %></td>
          <td><%= stat.seen_pct.nil? ? 'n/a' : number_to_percentage(stat.seen_pct*100, precision: 1)%></td>
          <td><%= stat.total %></td>
          <td><%= stat.per_page %></td>
            <%- Settings.display_percentiles.each do |pct| -%>
              <td><%= stat.send("pct_#{pct}") %></td>
            <%- end -%>
        </tr>
      <%- end -%>
      </tbody>
    </table>

  </div>
</div>

app/views/pages/comparison_test.html.erb
<%- @page_title = "Comparing News To Indexed News "-%>
<header class="jumbotron subhead" id="overview">
  <h1><%= @page_title %></h1>
  <p class="lead">Data for <%= year_week_for_last_week%> (<%= date_range_for_last_week%>)</p>
</header>

<div class="row">
  <div class="span12">
    <h3><%= @datatype %> growth</h3>
    <%= render(partial: 'shared/comparison_plot', locals: {:data => @stats.to_graph_data('pages',{showrolling: false}), :datalabel => 'pagegrowth', :labels => @stats.to_graph_labels})%>
  </div>
</div>

<div class="row">
  <div class="span12">
    <h3>% Viewed</h3>
    <%= render(:partial => 'shared/comparison_plot', :locals => {:data => @stats.to_graph_data('seen',{relative_to: 'pages', relative_percentage: true, showrolling: false}), :labels => @stats.to_graph_labels, :datalabel => 'seen_pct', :ymax => 100})%>
  </div>
</div>


<div class="row">
  <div class="span12">
  <h3>Views</h3>
    <%= render(:partial => 'shared/comparison_plot', :locals => {:data => @stats.to_graph_data('per_page'), :datalabel => 'views', :labels => @stats.to_graph_labels})%>
  </div>
</div>

app/views/pages/details.html.erb
<%- if @contributor -%>
  <%= render(:partial => 'contributor_page_breadcrumbs', :locals => {:endpoint => @endpoint}) %>
<%- elsif @group -%>
  <%= render(:partial => 'group_page_breadcrumbs', :locals => {:endpoint => @endpoint}) %>
<%- else -%>
  <%= render(:partial => 'page_breadcrumbs', :locals => {:endpoint => @endpoint}) %>
<%- end -%>
<header class="jumbotron subhead" id="overview">
  <h1><%= @page_title_display.html_safe %></h1>
  <p class="lead">Data for <%= year_week_for_last_week%> (<%= date_range_for_last_week%>)</p>
</header>

<div class="page-header">
  <h2>Summary</h2>
  <%- link_params = params.delete_if{|k,v| ['action'].include?(k)} -%>
  <p>
  <%= link_to("Aggregate Statistics By Week &raquo;".html_safe,aggregate_pages_path(link_params),:class => 'btn') if (@datatype != 'All' and !@contributor and !@tag)  %>
  <%= link_to("Individual Page Totals &raquo;".html_safe,totals_pages_path(link_params),:class => 'btn') %>
 </p>
</div>

<div class="row">
  <div class="span12">
    <h3><%= @datatype %> growth</h3>
    <%= render(partial: 'shared/line_plot', locals: {:data => @stats.to_graph_data('pages',{showrolling: false}), :datalabel => 'pagegrowth'})%>
  </div>
</div>

<div class="row">
  <div class="span12">
    <h3>% Viewed</h3>
    <%= render(:partial => 'shared/line_plot', :locals => {:data => @stats.to_graph_data('seen',{relative_to: 'pages', relative_percentage: true, showrolling: false}), :datalabel => 'seen_pct', :fill => true, :ymax => 100})%>
  </div>
</div>


<div class="row">
  <div class="span12">
  <h3>Views</h3>
    <%= render(:partial => 'shared/line_plot', :locals => {:data => @stats.to_graph_data('per_page'), :datalabel => 'views'})%>
  </div>
</div>


<div class="row">
  <div class="span12">
  <h3>Percentiles</h3>
    <p><em>click the legend labels to toggle display of the given item</em></p>
    <%= render(:partial => 'shared/comparison_plot', :locals => {:data => @percentiles.to_percentile_graph_data, :labels => @percentiles.to_percentile_graph_labels, datalabel: 'percentiles'})%>
  </div>
</div>

app/views/pages/group.html.erb
<% @page_title = "Page Information - Group ##{@group.id}" %>
<%= render(:partial => 'page_breadcrumbs', :locals => {:showgroups=> true, :group => @group}) %>
<header class="jumbotron subhead" id="overview">
  <h1>Page Information for <%= @group.name %></h1>
  <p class="lead">
    Data for <%= year_week_for_last_week%>
    (<%= date_range_for_last_week%>) 
  </p>
</header>

  <div class="page-header">
    <h2>Landing Page</h2>
  </div>  
  <div class="row">
    <div class="span4">
      <%- index_stats = @group.landing_diffs.latest_week.by_metric('views').first -%>
      <p><span class='bignumber'><%=number_with_precision(index_stats.total, :precision => 0)%></span> views for week</p>
      <p><%= pct_change(index_stats.pct_change_week,'mednumber') %> from previous week</p>
      <p><%= pct_change(index_stats.pct_change_year,'mednumber') %> from previous year</p>
      <p><%= trend(index_stats.recent_pct_change,'mednumber') %> trend/week (last <%=Settings.recent_weeks%> weeks)</p>
    </div>
  
    <div class="span8">
      <h3>Views per week over time</h3>
      <%= render(:partial => 'data_plot', :locals => {:data => @group.landing_diffs.by_metric('views').stats_to_graph_data, :datalabel => 'index'})%> 
    </div>
  </div>

<%- Page::DATATYPES.each do |datatype| -%>
  <div class="page-header">
    <h2><%= datatype.pluralize %></h2>
  </div>  
  <div class="row">
    <div class="span4">
      <%- stats_for_week_for_datatype = @group.stats_for_week_for_datatype(datatype) -%>
      <%- if stats_for_week_for_datatype[:pages] and stats_for_week_for_datatype[:pages] > 0 -%>   
        <%= render(:partial => 'overall_views_information', :locals => {:datatype => datatype, :stats_for_week => stats_for_week_for_datatype}) %>
        <p>
          <%= link_to("<i class='icon-th'></i> #{datatype.pluralize} list".html_safe,list_group_pages_path(:datatype => datatype, :group => @group.id),:class => 'btn btn-info') %>      
        </p>
      <%- else -%>
        No data.
      <%- end -%>
    </div>
  
    <%- if stats_for_week_for_datatype[:pages] and stats_for_week_for_datatype[:pages] > 0 -%>   
    <div class="span8">
      <h3>Views per week over time <small><%= link_to('more graphs...',graphs_pages_path(:datatype => datatype,:group => @group.id))%></small></h3>
      <%= render(:partial => 'graphs_plot', :locals => {:data => @group.graph_data_by_datatype(datatype), :datakey => "views", :datalabel => datatype, :ymax => @group.total_diffs.max_views(5)})%>     
    </div>
    <%- end -%>
  </div>
<%- end -%>

app/views/pages/grouplist.html.erb
<%= render(:partial => 'page_breadcrumbs', :locals => {:showgroups=> true, :endpoint => @endpoint}) %>
<header class="jumbotron subhead" id="overview">
  <h1><%= @page_title_display.html_safe %></h1>
  <p class="lead">Data for <%= year_week_for_last_week%> (<%= date_range_for_last_week%>) </p>
</header>

<div class="row">
  <div class="span12">
	  <%= paginate(@pagelist) %>
	  <%= render(:partial => 'pagelist', :locals => {:pagelist => @pagelist} )%>
  </div>
</div>

app/views/pages/groups.html.erb
<% @page_title = "Groups page information" %>
<%= render(:partial => 'page_breadcrumbs', :locals => {:endpoint => 'Groups'}) %>
<header class="jumbotron subhead" id="overview">
  <h1><%= @page_title %></h1>
  <p class="lead">Data for <%= year_week_for_last_week%> (<%= date_range_for_last_week%>) </p>
  
</header>


<div class="well">
  <%= text_field_tag("groupfinder",'',{:class => 'input search-query', :placeholder => 'Type and select to jump to group'}) %>
  <script class="code" type="text/javascript">
    $('#groupfinder').autocomplete({
      source: "/data/groups",
      minLength: 2,
      select: function(event, ui) { 
        window.location = '/pages/group/' + ui.item.id
      } 
    });
  </script>
</div>


<div class="page-header">
  <h1>Top Groups for Week
    <small>by average views/page</small>
  </h1>
</div> 

<div class="row">
  <%- Page::DATATYPES.each do |datatype| -%>
    <div class="span3">
      <div class="page-header">
        <h3><%= datatype.pluralize%></h3>
      </div> 
      <%- groupslist = Group.launched.top_views(:datatype => datatype) -%>
      <dl>
      <%- groupslist.each do |group| %>
        <%- group_stats = group.stats_for_week_for_datatype(datatype) -%>
        <dt><%= link_to(group.name, group_pages_path(group))%></dt>
        <dd><span class='regnumber'><%= number_with_precision(group_stats[:views], :precision => 2) %></span> views</dd>
        <dd><span class='regnumber'><%= number_to_percentage(group_stats[:seen]/group_stats[:pages]*100, :precision => 1) %></span>
        of <span class='regnumber'><%= number_with_delimiter(group_stats[:pages])%></span> items viewed</dd>
      <%- end -%>
      </dl>      
    </div>
  <%- end -%>
</div>

app/views/pages/index.html.erb
<% @page_title = "Page Information" %>
<%= render(:partial => 'page_breadcrumbs', :locals => {:endpoint => 'Pages'}) %>

<header class="jumbotron subhead" id="overview">
  <h1><%= @page_title %></h1>
  <p class="lead">Data for <%= year_week_for_last_week%> (<%= date_range_for_last_week%>) </p>
</header>

<div class="page-header">
  <h2>Overall</h2>
</div>

<div class="row">
  <div class="span8">
    <h3>Home Page Views</h3>
    <%= render(:partial => 'shared/line_plot', :locals => {:data => @landing_stats.to_graph_data('total'), :datalabel => 'index'})%>
  </div>

  <div class="span4">
    <h3>Home Page Stats</h3>
    <p><span class='bignumber'><%=number_with_precision(@landing_stats[@latest_yearweek]['total'], :precision => 0)%></span> views for week</p>
    <p><%= pct_change(@landing_stats[@latest_yearweek]['pct_change_week'],'mednumber') %> from previous week</p>
    <p><%= pct_change(@landing_stats[@latest_yearweek]['pct_change_year'],'mednumber') %> from previous year</p>
  </div>
</div>

<div class="page-header">
  <h2>Page Types</h2>
</div>
<div class="row">
  <%- Page::DATATYPES.each do |datatype| -%>
    <div class="span6">
      <h3><%= datatype.pluralize %> <span><%= link_to("details &raquo;".html_safe,
                     details_pages_path(datatype: datatype),:class => 'btn btn-small') %></span></h3>
      <%= render(:partial => 'shared/overall_views_information',
                 :locals => {:datatype => datatype, :stats_for_week => @datatype_stats[datatype][@latest_yearweek]}) %>

    </div>
  <%- end -%>
</div>

<div class="row">
  <div class="span12">
    <h3>Views</h3>
    <%= render(:partial => 'shared/comparison_plot',
               :locals => {data: @datatype_stats.to_graph_data('per_page'),
                           labels: @datatype_stats.to_graph_labels,
                           datalabel: "per_page" }) -%>
  </div>
</div>

<div class="row">
  <div class="span12">
    <h3>% Viewed</h3>
    <%= render(:partial => 'shared/comparison_plot',
               :locals => {data: @datatype_stats.to_graph_data('seen',{relative_to: 'pages', relative_percentage: true}),
                           labels: @datatype_stats.to_graph_labels,
                           datalabel: "seen_pct",
                           ymax: 100 }) -%>
  </div>
</div>

app/views/pages/overview.html.erb
<%- if @contributor -%>
  <%= render(:partial => 'contributor_page_breadcrumbs', :locals => {:endpoint => @endpoint}) %>
<%- elsif @group -%>
  <%= render(:partial => 'group_page_breadcrumbs', :locals => {:endpoint => @endpoint}) %>
<%- else -%>
  <%= render(:partial => 'page_breadcrumbs', :locals => {:endpoint => @endpoint}) %>
<%- end -%>
<header class="jumbotron subhead" id="overview">
  <h1><%= @page_title_display.html_safe %></h1>
  <p class="lead">Data for <%= year_week_for_last_week%> (<%= date_range_for_last_week%>)</p>
</header>

<div class="row">
  <%- Page::DATATYPES.each do |datatype| -%>
    <div class="span3">
      <%- if @datatype_stats[datatype][@latest_yearweek] -%>
        <h3><%= datatype.pluralize %>
          <%- link_params = params.delete_if{|k,v| ['action'].include?(k)}.merge({datatype: datatype}) -%>
          <span><%= link_to("details &raquo;".html_safe,details_pages_path(link_params),:class => 'btn btn-small') %></span>
        </h3>
        <%= render(:partial => 'shared/overall_views_information',
                   :locals => {:datatype => datatype, :stats_for_week => @datatype_stats[datatype][@latest_yearweek]}) %>
     <%- else -%>
       <h3><%= datatype.pluralize %></h3>
       <p> No Data </p>
     <%- end -%>
    </div>
  <%- end -%>
</div>

<%- Page::DATATYPES.each do |datatype| -%>
<%- if @datatype_stats[datatype][@latest_yearweek] -%>
<div class="row">
  <div class="span12">
    <h3><%= "#{datatype} Views vs. Overall average" %></h3>
    <%= render(:partial => 'shared/comparison_plot',
               :locals => {data: @comparators[datatype].to_graph_data('per_page'),
                           labels: @comparators[datatype].to_graph_labels,
                           datalabel: "per_page_#{datatype}" }) -%>
  </div>
</div>
<%- end -%>
<%- end -%>

app/views/pages/search.html.erb
<% @page_title = "Search Results" %>
<%= render(:partial => 'page_breadcrumbs', :locals => {:endpoint => "search"}) %>
<header class="jumbotron subhead" id="overview">
  <h1><%= @page_title %></h1>
</header>

<%= form_tag(search_pages_path, { :class => 'well form-search ' }) do -%>
<%= text_field_tag :q, params[:q], {:class => 'search-query', :placeholder => 'Find page (title, page id, or node id)', :autocomplete => 'off'} -%>
<%- end -%>

<div class="row">
  <%- if @page or @node -%>
    <%- if @page -%>
      <div class="span6">
        <h3>Page ID results</h3>
        <p>Found page #<%= @page.id %>: <%= link_to(@page.title,page_path(@page))%></p>
      </div>
    <%- end -%>
    <%- if @node -%>
      <div class="span6">
        <h3>Node ID results</h3>
        <p>Found node #<%= @node.id%>: <%= link_to(@node.title,node_path(@node))%></p>
      </div>
    <%- end -%>
  <%- elsif(@pagelist) -%>
  <div class="span12">
    <h3>Pages matching <%= params[:q]%></h3>
    <ul class="unstyled">
      <%- @pagelist.each do |page| -%>
      <li><%= link_to(page.title,page_path(page))%></li>
      <%- end -%>
    </ul>
  </div>
  <%- else -%>
  <div class="span12">
    <p>No results. Please search again</p>
  </div>
  <%- end -%>

</div>

app/views/pages/show.html.erb
<% @page_title = "Details for Page ##{@page.id}" %>
<%= render(:partial => 'page_breadcrumbs', :locals => {:endpoint => "#{@page.id}"}) %>
<header class="jumbotron subhead" id="overview">
  <h1><%= @page_title %></h1>
  <p class="lead">Data for <%= year_week_for_last_week%> (<%= date_range_for_last_week%>) </p>
</header>

<div class="row">
  <div class="span7">
    <table class="table table-condensed">
      <tbody>
      <tr>
        <td>Title</td>
        <td><%= @page.title %></td>
      </tr>
      <tr>
        <td>Published URL</td>
        <td><%= link_to("http://www.extension.org/pages/#{@page.id}/#{@page.url_title}","http://www.extension.org/pages/#{@page.id}/#{@page.url_title}")%></td>
      </tr>
      <tr>
        <td>Source URL</td>
        <td><%= link_to(@page.source_url,@page.source_url)%></td>
      </tr>
    <tr>
      <td>More Information</td>
      <td><%= link_to("http://www.extension.org/pageinfo/#{@page.id}","http://www.extension.org/pageinfo/#{@page.id}")%></td>
    </tr>
    </tbody>
  </table>
 </div>

  <div class="span5">
    <%= render(:partial => 'page_views_information', :locals => {:page => @page}) %>
  </div>
</div>

<div class="row">
  <div class="span12">
  </div>
</div>

<div class="row">
  <div class="span12">
	 <h3>Page Information</h3>
   <%- if(!@page.node.nil?) -%>
   <p><%= link_to("Node ##{@page.node.id} &raquo;".html_safe,node_path(@page.node), class: 'btn')%></p>
   <%- end -%>
   <%= render(partial: 'page_information_table') %>
  </div>
</div>

<div class="page-header">
   <h3>Page Views By Week <%= button_tag("Show Details &raquo;".html_safe, id: 'infotoggler', class: 'btn btn-small', data: {toggle: 'collapse', target: '#showinfo'}) %></h3>
</div>

<div class="row">
  <div class="span12">
    <%= render(:partial => 'shared/line_plot', :locals => {:data => @view_stats.to_graph_data('total'), :datalabel => 'views'})%>
  </div>
</div>
<div id="showinfo" class="collapse">
  <hr/>
  <div class="row">
    <div class="span12">
        <%= render(partial: 'page_stats_table') %>
    </div>
  </div>
 </div>



<script type="text/javascript">

$('#showinfo').on('show', function () {
  $('#infotoggler').html('Hide Details &laquo;');
});

$('#showinfo').on('hide', function () {
  $('#infotoggler').html('Show Details &raquo;');
});

</script>

app/views/pages/totals.html.erb
<%- if @contributor -%>
  <%= render(:partial => 'contributor_page_breadcrumbs', :locals => {:endpoint => @endpoint}) %>
<%- elsif @group -%>
  <%= render(:partial => 'group_page_breadcrumbs', :locals => {:endpoint => @endpoint}) %>
<%- else -%>
  <%= render(:partial => 'page_breadcrumbs', :locals => {:endpoint => @endpoint}) %>
<%- end -%>
<header class="jumbotron subhead" id="overview">
  <h1><%= @page_title_display.html_safe %></h1>
  <p class="lead">Data for <%= year_week_for_last_week%> (<%= date_range_for_last_week%>)
  <%- link_params = params.merge({download: 'csv'}) -%>
  <span class='pull-right'><%= link_to("<i class='icon-file'></i>Download (.csv)".html_safe,link_params,:class => 'btn') %></span></p>
</header>

<div class="row">
  <div class="span12">
	  <%= paginate(@pagelist) %>

    <table class="table table-bordered table-striped sortable">
      <thead>
        <tr>
            <%= sortable_th(column: 'id', title: '#', direction: 'asc') %>
            <%= sortable_th(column: 'title', title: 'Title', direction: 'asc') %>
            <%= sortable_th(column: 'total_weeks', title: 'Weeks Published', direction: 'desc') %>
            <%= sortable_th(column: 'total', title: 'Total Views', direction: 'desc') %>
            <%= sortable_th(column: 'mean', title: 'Average Views', direction: 'desc') %>
            <%= sortable_th(column: 'this_week', title: 'This Week', direction: 'desc') %>
            <%= sortable_th(column: 'pct_change_week', title: '% Change Week', direction: 'desc') %>
            <%= sortable_th(column: 'pct_change_year', title: '% Change Year', direction: 'desc') %>
        </tr>
      </thead>

      <tbody>
        <%- for page in @pagelist -%>
        <tr>
          <td><%= page.id %></td>
          <%- if page.title.blank?
              title = '(blank)'
            else
              title = page.title.truncate(40, :separator => '...')
            end -%>
          <td><%= link_to(title,page_path(page)) %></td>
          <td><%= page.total_weeks %></td>
          <td><%= page.try(:total) %></td>
          <td><%= page.try(:mean) %></td>
          <td><%= page.try(:this_week) %></td>
          <td><%= pct_change(page.pct_change_week)%></td>
          <td><%= pct_change(page.pct_change_year)%></td>
        </tr>
      <%- end -%>
      </tbody>
    </table>

  </div>
</div>